export const defaultRestaurantConfig = {
  name: "BURGER KINGO",
  slogan: "La Verdadera Bestia",
  tagline: "Carne 100% roast beef, pan de papa y nuestra salsa secreta",
  phone: "+5492610000000", // WhatsApp number
  address: "Av. San Martín 1234, Centro, Mendoza",
  mapUrl: "", // Optional: specific address or coordinates for the map
  location: "Estamos en pleno centro de Mendoza",
  hours: {
    weekdays: "Lunes a Viernes: 12:00 - 15:00 | 19:00 - 00:00",
    weekends: "Sábados y Domingos: 12:00 - 01:00",
  },
  deliveryOptions: ["Retiro en local", "Delivery a domicilio", "Pedí por WhatsApp"],
  socialMedia: {
    instagram: "@burgerkingo",
    facebook: "BurgerKingoOficial",
  },
  promos: [
    {
      id: "promo-1",
      title: "3x2 en Burgers",
      description: "Tres Bestias Originales por el precio de dos. ¡Ideal para compartir!",
      price: 9000,
      urgency: "Solo por tiempo limitado",
    },
    {
      id: "promo-2",
      title: "Pack Finde",
      description: "2 Kingo BBQ + 1 Papas Cheddar Gigantes + 2 Pintas de Cerveza",
      price: 12500,
      urgency: "Viernes y Sábados",
    },
    {
      id: "promo-3",
      title: "Family Box",
      description: "4 Hamburguesas a elección + 2 Papas Grandes + 1 Gaseosa 1.5L",
      price: 18000,
      urgency: "Todos los días",
    },
  ],
  menuItems: [
    {
      id: 1,
      name: "La Bestia Original",
      description: "Doble carne de roast beef, queso cheddar, bacon, cebolla caramelizada",
      price: 4500,
      category: "Hamburguesas",
      image: "/gourmet-double-burger-with-cheese-and-bacon-dark-b.jpg",
    },
    {
      id: 2,
      name: "Kingo BBQ",
      description: "Carne de roast beef, queso ahumado, salsa BBQ casera, aros de cebolla",
      price: 4200,
      category: "Hamburguesas",
      image: "/bbq-burger-with-onion-rings-dark-background.jpg",
    },
    {
      id: 3,
      name: "Crispy Chicken",
      description: "Suprema crocante, lechuga, tomate, salsa especial de la casa",
      price: 3800,
      category: "Hamburguesas",
      image: "/crispy-chicken-burger-dark-background.jpg",
    },
    {
      id: 4,
      name: "Veggie Deluxe",
      description: "Medallón de quinoa y vegetales, queso, palta, rúcula",
      price: 3500,
      category: "Hamburguesas",
      image: "/vegetarian-burger-with-avocado-dark-background.jpg",
    },
    {
      id: 5,
      name: "Papas Clásicas",
      description: "Papas fritas caseras con sal marina",
      price: 1500,
      category: "Papas",
      image: "/golden-french-fries-dark-background.jpg",
    },
    {
      id: 6,
      name: "Papas Cheddar Bacon",
      description: "Papas con queso cheddar fundido, bacon crocante y cebollita de verdeo",
      price: 2200,
      category: "Papas",
      image: "/loaded-cheese-fries-with-bacon-dark-background.jpg",
    },
    {
      id: 7,
      name: "Coca Cola",
      description: "Lata 354ml",
      price: 800,
      category: "Bebidas",
      image: "/soda-can-dark-background.jpg",
    },
    {
      id: 8,
      name: "Cerveza Artesanal",
      description: "Pinta 500ml - IPA o Rubia",
      price: 1800,
      category: "Bebidas",
      image: "/craft-beer-glass-dark-background.jpg",
    },
  ],
  testimonials: [
    {
      id: 1,
      name: "Martín G.",
      rating: 5,
      comment: "Las mejores hamburguesas de Mendoza, sin dudas. La carne es de otro nivel.",
    },
    {
      id: 2,
      name: "Carolina R.",
      rating: 5,
      comment: "Me encanta la Bestia Original, siempre que puedo voy. El pan de papa es espectacular.",
    },
    {
      id: 3,
      name: "Rodrigo M.",
      rating: 5,
      comment: "Excelente atención y las papas cheddar bacon son adictivas. 100% recomendable.",
    },
    {
      id: 4,
      name: "Lucía F.",
      rating: 5,
      comment: "La mejor relación calidad-precio. Siempre llegan perfectas por delivery.",
    },
  ],
  promo: {
    title: "Promo Jueves 2x1",
    description: "Todos los jueves 2x1 en burgers seleccionadas",
    urgency: "Solo los jueves de 19:00 a 23:00",
  },
}
